[package]
name = "graphviz"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "graphviz"
path = "lib.rs"

[dependencies]
std = { path = "../libstd", default-features = false }
