[package]
name = "collections"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "collections"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
alloc = { path = "../liballoc" }
rustc_unicode = { path = "../librustc_unicode" }
