[package]
name = "flate"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "miniz"
build = "build.rs"

[lib]
name = "flate"
path = "lib.rs"

[dependencies]
std = { path = "../libstd", default-features = false }

[build-dependencies]
gcc = "0.3"
