#!/bin/bash
set -eu

if [ $# -lt 1 ]; then
	echo Usage: $0 TARGET [LLVM_CONFIG]
	echo ex: $0 x86_64-unknown-linux-gnu /usr/bin/llvm-config
	exit 1
fi

ROOT="$PWD"
TARGET="$1"

if [ $# -lt 2 ]; then
	LLVM_CONFIG="$ROOT/$TARGET/llvm/Release/bin/llvm-config"
	shift 1
else
	LLVM_CONFIG="$2"
	shift 2
fi

HOST=`$LLVM_CONFIG --host-target`

export RUSTC="$ROOT/rustc-sysroot"
export RUST_TARGET_PATH="$ROOT"
export CARGO_TARGET_DIR="$ROOT/target"
export CFG_LLVM_LINKAGE_FILE="$CARGO_TARGET_DIR/$TARGET/llvmdeps.rs"
export CFG_COMPILER_HOST_TRIPLE="$HOST"
export CFG_LLVM_CONFIG="$LLVM_CONFIG"
export CFG_LLVM_STDCPP="stdc++"

export CARGO_TARGET_DIR="$ROOT/target/std"
cargo build --manifest-path "$ROOT/Cargo.toml" --target $TARGET --features libstd "$@"
#cargo build --manifest-path "$ROOT/Cargo.toml" --target $TARGET --features libstd_light "$@"

SYSROOT="$CARGO_TARGET_DIR/lib/rustlib/$TARGET"
mkdir -p "$SYSROOT/lib"
ln -sf "$CARGO_TARGET_DIR/$TARGET/debug/deps/lib"{alloc,backtrace,collections,compiler_rt,core,libc,rand,rust_builtin,rustc_bitflags,rustc_unicode,system,std}*.rlib "$SYSROOT/lib/"
ln -sf "$CARGO_TARGET_DIR/$TARGET/debug/deps/libcompiler_rt.a" "$SYSROOT/lib/"

export CARGO_TARGET_DIR="$ROOT/target/non-std"
export RUSTC_SYSROOT="$SYSROOT/../../../"
cargo build --manifest-path "$ROOT/Cargo.toml" --target $TARGET --features deps "$@"
ln -sf "$CARGO_TARGET_DIR/$TARGET/debug/deps/lib"{arena,collectionstest,coretest,fmt_macros,flate,getopts,graphviz,log,rbml,serialize,syntax,term,test}*.rlib "$SYSROOT/lib/"

export CARGO_TARGET_DIR="$ROOT/target/staging"
export CFG_LLVM_LINKAGE_FILE="$CARGO_TARGET_DIR/$TARGET/llvmdeps.rs"
#cargo test --manifest-path "$ROOT/src/libsystem/Cargo.toml" --target $TARGET --no-default-features --features "compiler-rt backtrace rust_builtin" "$@"
#cargo test --manifest-path "$ROOT/src/libstd/Cargo.toml" --target $TARGET --no-default-features --features "compiler-rt backtrace rust_builtin" "$@"
#exit
#cargo build --manifest-path "$ROOT/Cargo.toml" --target $TARGET --features libstd "$@"
cargo build --manifest-path "$ROOT/src/librustc_driver/Cargo.toml" --target $TARGET --bin rustc "$@"
cargo build --manifest-path "$ROOT/src/librustdoc/Cargo.toml" --target $TARGET --bin rustdoc "$@"
cargo build --manifest-path "$ROOT/src/compiletest/Cargo.toml" --target $TARGET "$@"
cargo build --manifest-path "$ROOT/src/error-index-generator/Cargo.toml" --target $TARGET "$@"
