[package]
name = "getopts"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "getopts"
path = "lib.rs"
doctest = false

[dependencies]
std = { path = "../libstd" }

[dev-dependencies]
log = { path = "../liblog" }
