[package]
name = "rustc_back"
version = "1.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "rustc_back"
path = "lib.rs"

[dependencies]
rustc_llvm = { path = "../librustc_llvm" }
rustc_front = { path = "../librustc_front" }
