[package]
name = "compiler-rt"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "compiler_rt"
build = "build.rs"

[lib]
name = "compiler_rt"
path = "../dummy.rs"

[build-dependencies]
gcc = "0.3"
